const channelData = [
        { network: "FOX", channel: "2" },
        { network: "PBS", channel: "3" },
        { network: "NBC", channel: "4" },
        { network: "DETROIT 50", channel: "5" },
        { network: "CBS", channel: "6" },
        { network: "ABC", channel: "7" },
        { network: "CBC", channel: "9" },
        { network: "INSP", channel: "11" },
        { network: "USA", channel: "13" },
        { network: "ION", channel: "19" },
        { network: "CW", channel: "20" },
        { network: "MY TV", channel: "22" },
        { network: "TNT", channel: "23" },
        { network: "NICKELODEON", channel: "24" },
        { network: "CARTOON NETWORK", channel: "25" },
        { network: "DISNEY", channel: "26" },
        { network: "LIFETIME", channel: "27" },
        { network: "E", channel: "28" },
        { network: "COMEDY CENTRAL", channel: "29" },
        { network: "VH1", channel: "30" },
        { network: "MTV", channel: "31" },
        { network: "BALLY SPORTS", channel: "32" },
        { network: "ESPN", channel: "33" },
        { network: "ESPN2", channel: "34" },
        { network: "FXX", channel: "35" },
        { network: "AMC", channel: "36" },
        { network: "TLC", channel: "37" },
        { network: "FREEFORM", channel: "38" },
        { network: "TBS", channel: "39" },
        { network: "HGTV", channel: "40" },
        { network: "TCM", channel: "41" },
        { network: "FOOD", channel: "42" },
        { network: "CMT", channel: "43" },
        { network: "SCI FI", channel: "45" },
        { network: "A&E", channel: "46" },
        { network: "HISTORY", channel: "47" },
        { network: "DISCOVERY", channel: "48" },
        { network: "CNBC", channel: "49" },
        { network: "CNN", channel: "50" },
        { network: "HLN", channel: "51" },
        { network: "MSNBC", channel: "52" },
        { network: "HALLMARK", channel: "53" },
        { network: "C-SPAN", channel: "54" },
        { network: "TRVL", channel: "56" },
        { network: "PARAMOUNT", channel: "57" },
        { network: "BET", channel: "58" },
        { network: "BRAVO", channel: "59" },
        { network: "GOLF", channel: "60" },
        { network: "FOX NEWS", channel: "61" },
        { network: "WEATHER", channel: "62" },
        { network: "FX", channel: "64" },
        { network: "LMN", channel: "65" },
        { network: "TV LAND", channel: "66" },
        { network: "ANIMAL PLANET", channel: "67" },
        { network: "OWN", channel: "68" },
        { network: "NAT GEO", channel: "69" },
        { network: "FS1", channel: "70" },
        { network: "HALLMARK MYSTERY", channel: "71" },
        { network: "NEWS NATION", channel: "72" },
        { network: "SUNDANCE", channel: "73" },
        { network: "IFC", channel: "74" },
        { network: "TENNIS", channel: "75" },
        { network: "BBC", channel: "76" },
        { network: "FXM", channel: "77" },
        { network: "FS2", channel: "78" },
        { network: "MTV2", channel: "81" },
        { network: "TRU", channel: "82" },
        { network: "ID", channel: "83" },
        { network: "FOX BUSINESS", channel: "84" },
        { network: "CBS SPORTS", channel: "85" },
        { network: "NBC", channel: "86" },
        { network: "BIG 10", channel: "87" },
        { network: "NICK TOONS", channel: "88" },
        { network: "CHEDDAR", channel: "89" },
        { network: "NEWS MAX", channel: "90" },
        { network: "ONE", channel: "91" },
        { network: "CLEO", channel: "92" },
        { network: "BOUNCE", channel: "101" },
        { network: "COZI", channel: "130" },
        { network: "H&I", channel: "132" },
        { network: "START", channel: "133" },
        { network: "BUZZR", channel: "134" },
        { network: "COMET", channel: "135" },
        { network: "CHARGE", channel: "136" },
        { network: "COZI", channel: "137" },
        { network: "H&I", channel: "176" },
        { network: "CSPAN2", channel: "188" },
        { network: "CSPAN3", channel: "189" },
        { network: "DAYSTAR", channel: "192" },
        { network: "TBN", channel: "193" },
        { network: "SBN", channel: "194" },
        { network: "BALLY SPORTS DETROIT", channel: "195" },
        { network: "ME TV", channel: "196" },
        { network: "ANTENNA TV", channel: "197" },
    ];